### ISSUE TITLE
1-3年生の顔合わせをする

### ISSUE THREAD

**Issue by kvvzr** [keitalab/lab#5]

**Comment by odkey** [comment]
方法として有力なのは
- 6Fクロスフィールドラウンジでピザパ
- 1Fカフェテリアでオードブル等頼む
- 1108で25+1(先生)つめつめのピザパ（一回全員詰めてみたいという好奇心）

などがありますかねー

**Comment by odkey** [comment]
実験室で懇親会的なことするのダメなんだっけそういえば

**Comment by mactkg** [comment]
学食で出来るんだからそっち使ってくれと言われそうな気もする
1108で出来るといろいろ良いところがあるんですけどね、話のネタが転がってるとか、ネタが湧いた時に色々話せるかなとか
全員詰めたらどうなるのかなというのも気になる

**Comment by mactkg** [comment]
これ担当決めたほうが良さそう

**Comment by odkey** [comment]
そうですね

**Comment by mactkg** [comment]
```
mactkg [6:27 PM] 
bot 掃除してよ

botBOT [6:27 PM] 
やだよ〜　剣道おじさんやってよ〜〜
```

剣道おじさん is 誰 @keitalab/1st

**Comment by mactkg** [comment]
とりあえずもう一人。

```
mactkg [6:28 PM] 
bot 掃除してよ

botBOT [6:28 PM] 
やだよ〜　tkkwやってよ〜〜
```

ということでおみくじ引いてみたら @ryosuketakakuwa になった。

**Comment by kvvzr** [comment]
1年生「火・木以外」

**Comment by kvvzr** [comment]
「渾身の懇親会」

**Comment by mactkg** [comment]
> 1Fカフェテリアでオードブル等頼む

について聞いてきたとのこと
- 4日以上前に言う
- 事務にも話を通す
- 土曜日もあけられる
  - 相談してくれればOK
- アルコール入れて2k〜
  - どちらかと言うと予算を行って欲しい
  - 未成年が居ても一律2k

**Comment by mactkg** [comment]
@ryosuketakakuwa この件どんなかんじでしょ

**Comment by ryosuketakakuwa** [comment]
夕方(16:00or17:00くらい)から1Fカフェテリアでパーティーという感じしか決めていません.
なにか企画してもいいんですが,いい案あれば是非.
値段は一律2kでよいかなという感じはしています.

**Comment by mactkg** [comment]
@ryosuketakakuwa 事務にも話すってなると月曜にはこの件話しないとですね

**Comment by mactkg** [comment]
っていうかもうすすんでんのかな

**Comment by mactkg** [comment]
ひとまず終了〜。振り返り記事書いたらクローズする

**Comment by mactkg** [comment]
お疲れ様でした
