### ISSUE TITLE
ディスカッションをまとめる何か

### ISSUE THREAD

**Issue by odkey** [keitalab/lab#6]
今日突然ディスカッションタイムが始まったけども、そのprocessやconclusionをlogとして残しておくシステムが何か欲しい。
現実味のある順に写真、音声、テキストなどのメディアがある（気がするけど）ので、それを何らかの形で共有、参照などできるようにしておきたい。

**Comment by mactkg** [comment]
wishって要望? labelとかあるのでそれ活用するといいかもしれない

**Comment by kvvzr** [comment]
権限がないので新しいlabelが作れません〜〜〜

**Comment by mactkg** [comment]
@kvvzr どうですか

**Comment by kvvzr** [comment]
@mactkg すばやい

**Comment by mactkg** [comment]
@kvvzr すばやい
