### ISSUE TITLE
wikiの編集が止まっている

### ISSUE THREAD

**Issue by odkey** [keitalab/lab#7]
wikiの編集を進めたい。
webのフォーマットとの兼ね合いで、wikiには何を書いていったらいいかまとめておきたいというのはあるな

**Comment by mactkg** [comment]
知ってる人が限られているのが問題な気がする。例えば3Dプリンターの使い方教えてもらったら教えてもらった人がWikiを更新するみたいにすると良いと思う。

**Comment by mactkg** [comment]
> 知ってる人が限られているのが問題な気がする。

というのは、結局書く人がおなじになってしまってくたびれるんじゃないか、それが問題かもという考えです。

**Comment by odkey** [comment]
機材、ソフト使い方のあたりはそうですね。

**Comment by mactkg** [comment]
とりあえず教わった人が書くということにしましょう
