### ISSUE TITLE
企画: ビブリオランチ

### ISSUE THREAD

**Issue by mactkg** [keitalab/lab#9]
> 伊藤大智 @14d5itoh
> ためになりそうな本とか内容箇条書きにして欲しい時ある。なんでこうなんだろうとか思ったとこだけ深く読みたいんだよね。 
> https://twitter.com/14d5itoh/status/590546904829796353
> 
> keita [1:09 AM] 
> みんな読んだ本をうちの研究室向けに、ざっくり紹介してくのはどうだ
> 
> mactkg [1:09 AM] 
> いいですね
> 
> keita [1:09 AM] 
> wikiでもいいけど。
> 
> 62grow2e [1:10 AM] 
> ビブリオバトル、とまでは言わないけど。。という
> 
> mactkg [1:10 AM] 
> ビブリオランチ

**Comment by mactkg** [comment]
というかもう少しランチとかの時間を活用してもいい気がしてる

**Comment by ryosuketakakuwa** [comment]
今週の金曜やりましょうやぁ〜〜〜各自本を持ち寄るぞい

**Comment by mactkg** [comment]
とりあえずおしまい
